sudo: false

language: node_js
node_js:
  - 4.2

cache:
  directories:
    - node_modules

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

branches:
  only:
    - master
